---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 04.08.18 18:14
---

local RPD = require "scripts/lib/commonClasses"
local actor = require "scripts/lib/actor"
local storage = require "scripts/lib/storage"
local mob = require "scripts/lib/mob"

local function updateLatestDeadMob(deadMob)
    local name = deadMob:getEntityKind()
    local counterId = name .." kills"
    local prevAmount = storage.get(counterId) or 0
    storage.put(counterId, prevAmount+1)
end

mob.installOnDieCallback(updateLatestDeadMob)

return actor.init({
    act = function()
        return true
    end,
    actionTime = function()
        return 1
    end,
    activate = function()
    end
})
