---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 02.05.19 14:36
---
local RPD  = require "scripts/lib/revampedCommonClasses"

local buff = require "scripts/lib/buff"

local immune = {"Charmed"}

local resistance = {"Succubus"}

local immuneMobs = {Goo=true,SpiderQueen=true,Lich=true,Tengu=true,IceGuardianCore=true,IceGuardian=true,DM300=true,Kind=true,ShadowLord=true,Yog=true,YogEye=true,YogBeain=true,YogHeart=true,YogTeeth=true,RottenFist=true,BurningFist=true,BoneDragon=true,LostSoul=true,GhostWarrior=true,GhostWarriorNPC=true,GhostAssassin=true,GhostArcher=true,GhostMage=true}

return buff.init{
    desc  = function ()
        return {
            icon          = 49,
            name          = "CharmfulBuff_Name",
            info          = "CharmfulBuff_Info",
        }
    end,

    attachTo = function(self, buff, target)
        return true
    end,

    detach = function(self, buff)
    end,

    act = function(self,buff)
        buff:spend(1)
    end,

    defenceProc = function(chr, buff, enemy, dmg)
        local chance = math.random(1,10)
        local chrKind = enemy:getEntityKind()
        if chance >= 5 then
            if not immuneMobs[chrKind] then
                RPD.affectBuff(enemy, RPD.Buffs.Charm, dmg/2+5)
                RPD.glogp(RPD.MobFactory:mobByName(chrKind):name().." has been charmed!")
            end
        end
        return dmg
    end,

    immunities = function(self, buff)
        return immune
    end,

    resistances = function(self, buff)
        return resistance
    end
}
