---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 02.05.19 14:36
---
local RPD  = require "scripts/lib/revampedCommonClasses"

local buff = require "scripts/lib/buff"

return buff.init{
    desc  = function ()
        return {
            icon          = 42,
            name          = "God Mode",
            info          = "God Mode for testing.",
        }
    end,

    attachTo = function(self, buff, target)
        return true
    end,

    detach = function(self, buff)
    end,

    act = function(self,buff)
        buff:spend(1)
    end,

    defenceProc = function(chr, buff, enemy, dmg)
        local chrKind = enemy:getEntityKind()
        RPD.glogn(RPD.MobFactory:mobByName(chrKind):name().." has delt "..tostring(dmg).." damage.")
        return 0
    end,

    attackProc = function(chr, buff, enemy, dmg)
        local chrKind = enemy:getEntityKind()
        RPD.glogp("You have delt "..tostring(dmg).." damage to "..RPD.MobFactory:mobByName(chrKind):name()..".")
        return dmg
    end,

    charAct = function(self,buff)
        local hero = RPD.Dungeon.hero
        hero:heal(hero:ht(), hero)
        hero:setSoulPoints(hero:getSkillPointsMax())
        hero:hunger():satisfy(hero:hunger():getHungerLevel())
    end
}
